## ndarray

In [51]:
import numpy as np

In [3]:
data = np.random.randn(2, 3)

In [4]:
data

array([[-0.35627091, -1.62528956,  1.03377382],
       [ 1.35888042, -0.71623408, -0.7857652 ]])

In [5]:
data*10

array([[ -3.56270915, -16.25289557,  10.33773818],
       [ 13.58880416,  -7.16234084,  -7.857652  ]])

In [6]:
data+data

array([[-0.71254183, -3.25057911,  2.06754764],
       [ 2.71776083, -1.43246817, -1.5715304 ]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]

In [10]:
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [-2.5, -1.89, 0.77, 12, 119]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([ -2.5 ,  -1.89,   0.77,  12.  , 119.  ])

In [15]:
arr1*arr2

array([-15.   , -14.175,   6.16 ,   0.   , 119.   ])

In [16]:
arr1 + arr2

array([  3.5 ,   5.61,   8.77,  12.  , 120.  ])

In [17]:
arr2 / arr1

<ipython-input-17-621d46aeda56>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr2 / arr1


array([-4.16666667e-01, -2.52000000e-01,  9.62500000e-02,             inf,
        1.19000000e+02])

In [18]:
data3 = [[12, 13, 14, 15], [21, 22, 23, 24]]

In [19]:
arr3 = np.array(data3)

In [20]:
arr3

array([[12, 13, 14, 15],
       [21, 22, 23, 24]])

In [21]:
arr2.ndim

1

In [22]:
arr3.ndim

2

In [23]:
arr3.shape

(2, 4)

In [24]:
arr3.dtype

dtype('int32')

In [25]:
arr2.dtype

dtype('float64')

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.zeros((3, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.empty((2, 3, 3))

array([[[3.70417447e-316, 5.33590898e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.15998412e-028],
        [2.44171989e+232, 8.00801729e+159, 3.48990054e-086]],

       [[3.44357007e-086, 3.44357007e-086, 3.44357007e-086],
        [3.44357007e-086, 5.79961754e+294, 1.43267083e+161],
        [4.56317366e-144, 4.82412328e+228, 1.04718130e-142]]])

In [30]:
arr5 = np.arange(15)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr5.dtype

dtype('int32')

In [32]:
arr5.astype(np.float16)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.], dtype=float16)

## Vetorização

In [33]:
arr3 ** 2

array([[144, 169, 196, 225],
       [441, 484, 529, 576]], dtype=int32)

In [34]:
arr3 / 2

array([[ 6. ,  6.5,  7. ,  7.5],
       [10.5, 11. , 11.5, 12. ]])

In [35]:
arr3 - arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
arr3.shape

(2, 4)

In [37]:
arr0 = np.zeros((2, 4))

In [38]:
arr3 > arr0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
arr3 <= arr0

array([[False, False, False, False],
       [False, False, False, False]])

In [40]:
arr3 == arr0

array([[False, False, False, False],
       [False, False, False, False]])

### Indexação

In [41]:
arr2[3]

12.0

In [42]:
arr2[:4]

array([-2.5 , -1.89,  0.77, 12.  ])

In [43]:
arr3[2:]

array([], shape=(0, 4), dtype=int32)

In [44]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr6[:] = 11

In [46]:
arr6

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [47]:
lista = [[1,2,3],[4,5,6]]
arr7 = np.array(lista)
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr7[1][1]=7

In [49]:
arr7

array([[1, 2, 3],
       [4, 7, 6]])

In [50]:
arr8 = np.arange(12)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr_slice = arr8[5:8]
arr_slice

array([5, 6, 7])

In [53]:
arr8[2:4] = 13
arr8

array([ 0,  1, 13, 13,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arr_copy = arr8[5:8].copy()
arr_copy

array([5, 6, 7])

In [55]:
arr_copy[:]=15
arr_copy

array([15, 15, 15])

In [56]:
arr8

array([ 0,  1, 13, 13,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
arr9 = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
arr9[2]

array([9, 8, 7])

In [59]:
arr9[1][0]

6

In [60]:
arr9[1, 0]

6

In [63]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3b = arr3d.copy()

In [65]:
arr3b[0]=43
arr3b

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[1, 0]

array([7, 8, 9])

##### Indexando com fatias

In [70]:
arr9

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [67]:
arr9[:1]

array([[3, 2, 1]])

In [68]:
arr9[1, :2]

array([6, 5])

In [69]:
arr9[:2, 2]

array([1, 4])

##### Indexação booleana